### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Enjoy1982** [Puntzi/pnt_bulletProofVest#2]
[      script:oxmysql] Error: pnt_bulletProofVest was unable to execute a query!
[      script:oxmysql] Query: SELECT * FROM bulletProof WHERE identifier = ?
[      script:oxmysql] ["steam:1100001012acb13"]
[      script:oxmysql] Table 'zap1114265-6.bulletProof' doesn't exist

how i can fix this??

**Comment by Puntzi** [comment]
Do you install the sql file?

**Comment by Enjoy1982** [comment]
hi, yes i have the sql also
![image](https://github.com/Puntzi/pnt_bulletProofVest/assets/136649939/497de775-4035-4b25-99a3-3a8e43cffff9)

**Comment by Enjoy1982** [comment]
![image](https://github.com/Puntzi/pnt_bulletProofVest/assets/136649939/55e93edb-66ea-4cf3-9f3d-6163eb86a471)

**Comment by Puntzi** [comment]
Hi, should be fixed if u re-download the script. Sry for the inconvinience

**Comment by Enjoy1982** [comment]
inconvinience? nothing man thx for everythink great job
