### ISSUE TITLE
Unlimited Vests 

### ISSUE THREAD

**Issue by LaCourDk** [Puntzi/pnt_bulletProofVest#3]
https://medal.tv/games/gta-v/clips/25Ntg0ggWNe5cY/d1337XKYjzo2?invite=cr-MSxjZVksMTY2NjAyNDI0LA 
:) if you spam the cormand you get multibel
think it neads a cooldown

**Comment by Puntzi** [comment]
I think with the last update it's fixed.

**Comment by LaCourDk** [comment]
We just got the Script 2 / 3 weeks ago :)

**Comment by Puntzi** [comment]
I updated it now

**Comment by LaCourDk** [comment]
Ohh Was not updaet At my page :D ! i wil check it out
